language: python

matrix:
    include:
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
          dist: xenial
          sudo: true
        - python: 3.7
          env: TOXENV=pep8
          dist: xenial
          sudo: true
        - python: pypy3
          env: TOXENV=pypy3

install:
  - pip install tox

script:
  tox

notifications:
  email: false
